import React, { useState } from 'react';
import { Copy, Check, Download, Box, Code2, Layers } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useBuilderStore } from "@/store/use-builder-store";
import { toast } from 'sonner';
interface BlockExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  blockName: string;
}
export function BlockExportDialog({ open, onOpenChange, blockName }: BlockExportDialogProps) {
  const canvasItems = useBuilderStore(s => s.canvasItems);
  const theme = useBuilderStore(s => s.theme);
  const [copied, setCopied] = useState(false);
  const generateCode = () => {
    const formattedName = blockName.replace(/\s+/g, '') || 'CustomBlock';
    const componentsCode = canvasItems.map(item => item.code).filter(Boolean).join('\n\n');
    return `/**
 * Generated by LeverageArchitecture
 * Theme: ${theme.fontFamily}, Primary: ${theme.primaryColor}, Radius: ${theme.borderRadius}px
 */
import React from 'react';
const ${formattedName} = () => {
  const containerStyle = {
    fontFamily: "'${theme.fontFamily}', sans-serif",
    borderRadius: '${theme.borderRadius * 2}px',
    '--primary': '${theme.primaryColor}',
  };
  return (
    <div style={containerStyle} className="leverage-block-container space-y-6 p-8">
      {/* Composed Primitives Start */}
      ${canvasItems.map(item => `
      <section className="leverage-primitive" data-primitive="${item.name}">
        {/* ${item.name} Implementation */}
        ${item.code?.split('\n').map(line => '        ' + line).join('\n').trim()}
      </section>`).join('\n')}
      {/* Composed Primitives End */}
    </div>
  );
};
export default ${formattedName};
`;
  };
  const fullCode = generateCode();
  const handleCopy = () => {
    navigator.clipboard.writeText(fullCode);
    setCopied(true);
    toast.success("Architectural block code copied");
    setTimeout(() => setCopied(false), 2000);
  };
  const handleDownload = () => {
    const blob = new Blob([fullCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${blockName.toLowerCase().replace(/\s+/g, '-') || 'block'}.tsx`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success("File download started");
  };
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[85vh] flex flex-col p-0 overflow-hidden border-none shadow-2xl">
        <DialogHeader className="p-6 bg-primary text-primary-foreground shrink-0">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-primary-foreground/10">
                <Layers className="size-6" />
              </div>
              <div>
                <DialogTitle className="text-2xl font-bold tracking-tight">Exporting {blockName || 'Architecture'}</DialogTitle>
                <DialogDescription className="text-primary-foreground/70">
                  Ready-to-use React component with global design tokens.
                </DialogDescription>
              </div>
            </div>
            <div className="flex gap-2">
              <Button variant="secondary" className="gap-2" onClick={handleDownload}>
                <Download className="size-4" /> Download .tsx
              </Button>
              <Button variant="default" className="gap-2 bg-white text-primary hover:bg-white/90" onClick={handleCopy}>
                {copied ? <Check className="size-4" /> : <Copy className="size-4" />}
                {copied ? 'Copied' : 'Copy Code'}
              </Button>
            </div>
          </div>
        </DialogHeader>
        <div className="flex-1 overflow-auto bg-slate-900 p-8 font-mono text-xs leading-relaxed scrollbar-thin scrollbar-thumb-slate-800">
          <div className="flex items-center gap-2 mb-4 text-slate-500 border-b border-slate-800 pb-2">
            <Code2 className="size-3" />
            <span className="uppercase tracking-widest font-bold">Generated Source</span>
          </div>
          <pre className="text-emerald-400">
            <code>{fullCode}</code>
          </pre>
        </div>
      </DialogContent>
    </Dialog>
  );
}