import React, { useState } from 'react';
import { Copy, Check, Download, Box, Code2, Layers, FileJson, Package, FileCode, Rocket } from 'lucide-react';
import JSZip from 'jszip';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useBuilderStore } from "@/store/use-builder-store";
import { toast } from 'sonner';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
interface BlockExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  blockName: string;
}
export function BlockExportDialog({ open, onOpenChange, blockName }: BlockExportDialogProps) {
  const canvasItems = useBuilderStore(s => s.canvasItems);
  const themePrimaryColor = useBuilderStore(s => s.theme.primaryColor);
  const themeBorderRadius = useBuilderStore(s => s.theme.borderRadius);
  const themeFontFamily = useBuilderStore(s => s.theme.fontFamily);
  const [copied, setCopied] = useState(false);
  const [isBundling, setIsBundling] = useState(false);
  const safeBlockName = (blockName || 'CustomBlock').replace(/\s+/g, '');
  const generateFiles = () => {
    const componentCode = `
import React from 'react';
import { motion } from 'framer-motion';
/**
 * ${blockName}
 * Generated by LeverageArchitecture
 */
export const ${safeBlockName}: React.FC = () => {
  return (
    <div className="leverage-block font-['${themeFontFamily}'] space-y-8 p-6" style={{
      '--primary': '${themePrimaryColor}',
      '--radius': '${themeBorderRadius}px'
    } as React.CSSProperties}>
      ${canvasItems.map(item => `
      {/* Primitive: ${item.name} */}
      <section className="primitive-wrapper w-full">
        ${item.code?.split('\n').join('\n        ').trim() || `<div>Missing component code for ${item.name}</div>`}
      </section>`).join('\n')}
    </div>
  );
};
export default ${safeBlockName};
`.trim();
    const tailwindConfig = `
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
      },
      borderRadius: {
        'lg': 'var(--radius)',
      },
      fontFamily: {
        'custom': ['${themeFontFamily}', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
`.trim();
    const packageJson = `
{
  "name": "@leverage/${safeBlockName.toLowerCase()}",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "framer-motion": "^10.0.0",
    "lucide-react": "^0.284.0",
    "clsx": "^2.0.0",
    "tailwind-merge": "^1.14.0"
  },
  "devDependencies": {
    "tailwindcss": "^3.3.0",
    "typescript": "^5.0.0"
  }
}
`.trim();
    const globalsCss = `
@tailwind base;
@tailwind components;
@tailwind utilities;
:root {
  --primary: ${themePrimaryColor};
  --radius: ${themeBorderRadius}px;
}
.leverage-block {
  font-family: '${themeFontFamily}', sans-serif;
}
`.trim();
    return { componentCode, tailwindConfig, packageJson, globalsCss };
  };
  const handleDownload = async () => {
    setIsBundling(true);
    const { componentCode, tailwindConfig, packageJson, globalsCss } = generateFiles();
    try {
      const zip = new JSZip();
      const root = zip.folder(safeBlockName.toLowerCase());
      root?.file(`${safeBlockName}.tsx`, componentCode);
      root?.file("package.json", packageJson);
      root?.file("tailwind.config.js", tailwindConfig);
      root?.file("globals.css", globalsCss);
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${safeBlockName.toLowerCase()}-bundle.zip`;
      link.click();
      URL.revokeObjectURL(url);
      toast.success("Project bundle downloaded", {
        description: "Includes Tailwind config and dependencies."
      });
    } catch (err) {
      toast.error("Failed to generate ZIP");
    } finally {
      setIsBundling(false);
    }
  };
  const { componentCode } = generateFiles();
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl max-h-[85vh] flex flex-col p-0 overflow-hidden border-none shadow-2xl bg-slate-950">
        <DialogHeader className="p-8 bg-primary text-primary-foreground shrink-0">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-2xl bg-white/10 backdrop-blur-md">
                <Rocket className="size-8" />
              </div>
              <div>
                <DialogTitle className="text-3xl font-extrabold tracking-tight">Project Architect Export</DialogTitle>
                <DialogDescription className="text-primary-foreground/80 font-medium">
                  Composed bundle ready for production React environments.
                </DialogDescription>
              </div>
            </div>
            <div className="flex gap-3">
              <Button variant="secondary" className="gap-2 h-11 px-6 font-bold" onClick={handleDownload} disabled={isBundling}>
                {isBundling ? "Bundling..." : <><Download className="size-4" /> Download Project ZIP</>}
              </Button>
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button variant="outline" className="h-11 px-6 bg-white/5 border-white/10 text-white hover:bg-white/10">
                      <Package className="size-4 mr-2" /> Publish to NPM
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Enterprise Feature: Direct CI/CD integration</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </div>
          </div>
        </DialogHeader>
        <div className="flex-1 flex overflow-hidden">
          <aside className="w-64 border-r border-slate-800 bg-slate-900/50 p-6 flex flex-col gap-6">
            <div>
              <h4 className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-4">Bundle Structure</h4>
              <div className="space-y-3">
                {[
                  { name: `${safeBlockName}.tsx`, icon: FileCode, active: true },
                  { name: 'package.json', icon: FileJson },
                  { name: 'tailwind.config.js', icon: FileCode },
                  { name: 'globals.css', icon: Layers }
                ].map((file) => (
                  <div key={file.name} className={`flex items-center gap-3 text-xs font-mono p-2 rounded-lg ${file.active ? 'bg-primary/20 text-primary border border-primary/20' : 'text-slate-400'}`}>
                    <file.icon className="size-4" />
                    <span>{file.name}</span>
                  </div>
                ))}
              </div>
            </div>
          </aside>
          <main className="flex-1 flex flex-col bg-slate-950">
            <div className="p-4 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2 text-slate-400">
                <Code2 className="size-4" />
                <span className="text-xs font-mono">{safeBlockName}.tsx</span>
              </div>
              <Button 
                variant="ghost" 
                size="sm" 
                className="text-slate-400 hover:text-white"
                onClick={() => {
                  navigator.clipboard.writeText(componentCode);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                  toast.success("Main component copied");
                }}
              >
                {copied ? <Check className="size-4 mr-2" /> : <Copy className="size-4 mr-2" />}
                Copy Code
              </Button>
            </div>
            <ScrollArea className="flex-1 p-8">
              <pre className="text-emerald-400 font-mono text-xs leading-relaxed">
                <code>{componentCode}</code>
              </pre>
            </ScrollArea>
          </main>
        </div>
      </DialogContent>
    </Dialog>
  );
}